void rules();
bool rule1();
bool rule2();
void rule3();
void rule4();
void eat();
void think();
bool canEat();
void getHungry();
int getSenderIndex(int senderId);
int getRandomNumber();
void simulateHungryCycle();
void initializeForksAndRequests();
void startGettingHungry(bool randomHungry);
